### ISSUE TITLE
support sparse6 format

### ISSUE THREAD

**Issue by schochastics** [mbojan/rgraph6#10]
described in http://users.cecs.anu.edu.au/~bdm/data/formats.txt
I'll put that on my agenda too

**Comment by mbojan** [comment]
Good idea!

**Comment by mbojan** [comment]
@schochastics is this something that you plan on working soon or "some day, some time"? 

I would like to push to CRAN sooner than later and the question is shall we include this or not. No rush, just logistics.

**Comment by schochastics** [comment]
I am working on it right now. I already have the dgraph6 ready. sparse6 seems a bit more complicated but I may have it ready later today

**Comment by mbojan** [comment]
Awesome!
