### ISSUE TITLE
fN() trips on numbers beyond integer range

### ISSUE THREAD

**Issue by mbojan** [mbojan/rgraph6#12]
The following test based on http://users.cecs.anu.edu.au/~bdm/data/formats.txt  (now turned-off) fails:

```r
for(n in round(seq(258048, 68719476735, length=10))) {
  test_that(
    paste0("fN(n) for n=", n), {
      r <- fN(n)
      expect_length(r, 8)
      expect_true(all(unlist(r) >= 63))
      expect_true(all(unlist(r) <= 126))
    })
}
```

Apparently goes beyond the integer range. Graphs of size up to 128  do work though.

**Comment by schochastics** [comment]
I'll have a look at the c++ code. Should be fixable with some "long long" formats. Worst case I have some `d2b` code that uses string representation
