### ISSUE TITLE
add examples

### ISSUE THREAD

**Issue by schochastics** [mbojan/rgraph6#16]
Files without examples (`find man -type f -iname "*.Rd" | xargs grep -L "\examples" | xargs grep "\name"`):

- [x] `man/graph_as_text.Rd:\name{graph_as_text}`
- [x] `man/choose_format.Rd:\name{choose_format}`
- [x] `man/network_from_text.Rd:\name{network_from_text}`
- [x] `man/from_graph6.Rd:\name{from_graph6}`
- [x] `man/sampleg6.Rd:\name{sampleg6}`
- [x] `man/edgelist_from_text.Rd:\name{edgelist_from_text}`
- [x] `man/read_file6.Rd:\name{read_file6}`
- [x] `man/read_file6.Rd:\item{path}{character; path to file name}`
- [x] `man/rgraph6-package.Rd:\name{rgraph6-package}`
- [x] `man/igraph_from_text.Rd:\name{igraph_from_text}`
- [x] `man/from_sparse6.Rd:\name{from_sparse6}`
- [x] `man/from_digraph6.Rd:\name{from_digraph6}`

**Comment by schochastics** [comment]
hijacking this issue: Anything left to do before submitting to CRAN?

**Comment by mbojan** [comment]
You are welcome @schochastics , I've made a list in issue description of files without examples. You can start from the top and I will from the bottom.

**Comment by mbojan** [comment]
> hijacking this issue: Anything left to do before submitting to CRAN?

Other than that, I wanted to have one last read through the documentation before submitting it to CRAN.

**Comment by schochastics** [comment]
Nice. I will look at the examples tonight and also have a look at the doc
