### ISSUE TITLE
Make a logo

### ISSUE THREAD

**Issue by mbojan** [mbojan/rgraph6#21]

**Comment by schochastics** [comment]
The encoding always reminds me of swearing in comics (called grawlix). Maybe playing with that would be something?
![](https://media.istockphoto.com/vectors/comic-book-with-cloud-and-cursing-vector-id1065946200?s=170667a)

**Comment by schochastics** [comment]
what do you think? the graph6 code represents the graph around the cloud (i.e. union of 2 P3, P2 and 2 P1).
![logo_rgraph6_full](https://user-images.githubusercontent.com/17147355/149467983-4fb107a7-1be0-4cb6-bbe5-e99d4dac0da6.png)

**Comment by mbojan** [comment]
Awesome. Can you make the networks more prominent?

I wonder how many ppl will infer that the package provides tools for automatic hate speech generation, e.g. towards R package developers? ;-)

**Comment by mbojan** [comment]
Perfect! Can you please commit it as `man/figures/logo.png`.
