### ISSUE TITLE
Write function(s) to read g6, s6, and d6 files directly

### ISSUE THREAD

**Issue by mbojan** [mbojan/rgraph6#24]
Should be a simple application of `readLines()`.

**Comment by schochastics** [comment]
What do you have in mind here?
I could think of the following:
```r
read_graph6 <- function(file, type = "adjacency"){
  type <- match.arg(type,c("adjacency","edgelist","igraph","network"))
  txt <- readLines(file)
  switch(type,
    "adjacency" = adjacency_from_graph6(txt),
    "edgelist"  = edgelist_from_text(txt),
    "igraph"    = igraph_from_graph6(txt),
    "network"   = network_from_graph6(txt)
  )
}

read_digraph6 <- function(file, type = "adjacency"){
  type <- match.arg(type,c("adjacency","edgelist","igraph","network"))
  txt <- readLines(file)
  switch(type,
         "adjacency" = adjacency_from_digraph6(txt),
         "edgelist"  = edgelist_from_text(txt),
         "igraph"    = igraph_from_digraph6(txt),
         "network"   = network_from_digraph6(txt)
  )
}

read_sparse6 <- function(file, type = "edgelist"){
  type <- match.arg(type,c("adjacency","edgelist","igraph","network"))
  txt <- readLines(file)
  switch(type,
         "adjacency" = adjacency_from_text(txt),
         "edgelist"  = edgelist_from_sparse6(txt),
         "igraph"    = igraph_from_graph6(txt),
         "network"   = network_from_graph6(txt)
  )
}
```
but there should probably also be a general function that reads mixed files (Had troubles coming up with a good name) 

```r
read_file6 <- function(file, type="adjacency"){
  type <- match.arg(type,c("adjacency","edgelist","igraph","network"))
  txt <- readLines(file)
  switch(type,
         "adjacency" = adjacency_from_text(txt),
         "edgelist" = edgelist_from_text(txt),
         "igraph"   = igraph_from_text(txt),
         "network"  = network_from_text(txt)
  )
}
```

what do you think?

**Comment by mbojan** [comment]
Thanks! Looks good. Some comments:

1. We need to pay attention to the optional headers such as `>>graph6<<` etc. See http://users.cecs.anu.edu.au/~bdm/data/formats.txt I've met users that use our package to read files generated with some other tools (such as Nauty) that include those headers. Reading mixed files will be a cherry on top.
2. Am I right that the functions only differ in terms of the default for the `type` argument? Perhaps there should be only one function with `format` argument? I'll think about it.

**Comment by mbojan** [comment]
Yeah, I guess one function is enough. I'll use yours above as a starting point and add handling of the optional headers.

**Comment by mbojan** [comment]
Added.

I'm wondering whether we should 

1. just drop potential header and let `*_from_text()` handle the type of the symbol 
2. implement some of logic that reads the header and errs if any of the symbols does not look like the format implied by the header?

Opinions @schochastics ?

**Comment by mbojan** [comment]
> 1. ~I think nauty doesnt produce headers (at least not the geng routine) but yeah,~(found the parameter for that...) headers should be automatically skipped. Though probably it should only be the standard headers (`>>graph6<<`,`>>sparse6<<`, and `>>digraph6<<`)? otherwise it might get too complicated. So some suggestions:
>        
>        * just parse out standard headers
>        * add a skip argument to let users handle any more complicated header
>        * use `scan()` with `comment.char = ">"`. This way we would enforce a standard comment character for such files.

Can there be more info in that header? Is that documented somewhere?

If the header has the form of `>>graph6 blahblah<<`  we could e.g.
```r
txt <- readLines("file")
txt[1] <- gsub("^>>[^<]+<<", "", txt[1]
```
and proceed as in your prototype above
