### ISSUE TITLE
Error with igraph 1.6.0 release candidate

### ISSUE THREAD

**Issue by krlmlr** [mbojan/rgraph6#35]
This package fails its checks for the release candidate for igraph 1.6.0. See <https://github.com/igraph/rigraph/blob/main/revdep/problems.md> for details.

Is this a problem in your package? Should we be doing things differently?

We're planning to release igraph 1.6.0 early December. This should give us at least until late mid-December, perhaps early January, to resolve this and keep CRAN happy at the same time. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/968.

**Comment by szhorvat** [comment]
This is fixed, just not yet released. See #34.

**Comment by mbojan** [comment]
Yep, that's fixed. I need to push to CRAN.

**Comment by krlmlr** [comment]
Thanks. Friendly reminder: we're releasing igraph 1.6.0 in early December.

**Comment by mbojan** [comment]
Thanks! I'll make sure to push to CRAN before that.
