### ISSUE TITLE
Compatibility with igraph 2.0.0

### ISSUE THREAD

**Issue by krlmlr** [mbojan/rgraph6#37]
@mbojan: This package fails its checks for the release candidate for igraph 2.0.0. See <https://github.com/igraph/rigraph/blob/igraph-0.10/revdep/problems.md> for details.

Is this a problem in your package? Should we be doing things differently?

Could be a duplicate of #35, haven't checked.

Install the 2.0.0 release candidate using `pak::pak("igraph/rigraph@igraph-0.10")` .

We're planning to release igraph 2.0.0 just before CRAN's closing on Christmas. This should give us at least until mid-January to resolve this and keep CRAN happy at the same time. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/989.

**Comment by mbojan** [comment]
Thanks Kirill. Yes, it's a duplicate. This problem (#34 and #35) is fixed and I submitted the new version to CRAN yesterday. Unfortunately it tripped some of the checks and will be resubmitting today. Thanks for the vigilance though!

**Comment by krlmlr** [comment]
Thank you!
