### ISSUE TITLE
`igraph::random.graph.game()` is deprecated

### ISSUE THREAD

**Issue by szhorvat** [mbojan/rgraph6#39]
Hi @mbojan, could you please remove uses of `random.graph.game` and replace them with `sample_gnp` / `sample_gnm`? This function has been considered outdated/deprecated for a long time now. As far as I can tell, it only appears in the README, where it can be replaced by `sample_gnp`.

https://github.com/mbojan/rgraph6/blob/8f854f19eb26caf2873f664efce6245d4cf4a29b/README.md?plain=1#L188

https://github.com/mbojan/rgraph6/blob/8f854f19eb26caf2873f664efce6245d4cf4a29b/README.Rmd#L182

**Comment by mbojan** [comment]
Thanks @szhorvat for the heads-up.
