### ISSUE TITLE
Function graph in README is broken

### ISSUE THREAD

**Issue by mbojan** [mbojan/rgraph6#41]
Graph of conversion functions is broken:

![image](https://github.com/user-attachments/assets/3b7940cd-efa3-40ec-8ef8-64e3852d2795)

Most likely due to upstream changes in edge labeling in **ggraph** (?)

**Comment by schochastics** [comment]
hmm this smells like a bug in ggraph. If you dont mind I investigate a bit

**Comment by mbojan** [comment]
Sure!
