### ISSUE TITLE
Matrix package deprecation msgs

### ISSUE THREAD

**Issue by mbojan** [mbojan/rgraph6#43]
Processing README and `as_sparse6()` generates:

```
#> 'as(<dgCMatrix>, "dgTMatrix")' is deprecated.
#> Use 'as(., "TsparseMatrix")' instead.
#> See help("Deprecated") and help("Matrix-deprecated").
```

**Comment by schochastics** [comment]
Interesting, I have Matrix version ‘1.7.0’ and I do not get the message

**Comment by mbojan** [comment]
It's ok ineed, gone when I re-rendered. Must have been a relict of the past.
