### ISSUE TITLE
Support larger graphs

### ISSUE THREAD

**Issue by mbojan** [mbojan/rgraph6#7]
Seems like the graph6 format supports larger graphs now http://users.cecs.anu.edu.au/~bdm/data/formats.txt

**Comment by mbojan** [comment]
Yes please! I dusted it off (I wrote first version 11 years ago =:o  !!) and it turns out it it does not pass the check any more. I moved to Rcpp and ended-up fighting memory corruption errors (I think). I'm C/C++ layman so it is flying blind for me a bit.

It will be awesome 🥇 if you could have a look and help me fix/extend it!!

**Comment by mbojan** [comment]
@schochastics I mean #9

**Comment by schochastics** [comment]
11 years ago I didnt even know what R was :joy:. 
I too am not very good with C/C++ but I give it a shot and report back
